<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));

function displayLinkToSolr($item, $field, $vocab) {
    if($item->value($vocab . ':' . $field[0])) {
        echo "<p>" . $field[1] . ": <a href=\"/s/MusicalInstruments/musical-instrument-search?q=*&limit%5B" . $vocab . "_" . $field[0] . "_s%5D%%B0%5D=" . $item->value($vocab . ':' . $field[0]) . "\">" . $item->value($vocab . ':' . $field[0]) . "</a></p>";
    }
}

function displayLinkToSolrMulti($field, $vocab, $value) {
    echo "<a href=\"/s/MusicalInstruments/musical-instrument-search?q=*&limit%5B" . $vocab . "_" . $field . "_ss%5D%%B0%5D=" . $value . "\">" . $value . "</a>";
}

$lightMedia = [];
$htmlMedia = [];
$audioMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if ((strpos($mediaType, 'image/') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else if (strpos($mediaRenderer, 'html') !== false) {
        $htmlMedia[] = $media;
    } else if (strpos($mediaType, 'audio/') !== false) {
        $audioMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php if (count($lightMedia) > 0): ?>
<ul id="itemfiles" class="media-list">
    <?php foreach ($lightMedia as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
        <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>" data-sub-html="<p><?php echo $media->value('dcterms:alternative'); ?></p>" class="media resource">
            <div class="caption"><?php echo $media->value('dcterms:title') . ": " . $media->value('dcterms:alternative');?></div>
            <?php echo $media->render(); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if (count($audioMedia) > 0): ?>
    <div class="media-embeds">
    <?php foreach ($audioMedia as $media):
        echo $media->render();
        echo $media->displayDescription();
    endforeach;
    ?>
    </div>
<?php endif; ?>

<?php if (count($htmlMedia) > 0): ?>
    <div class="html-embeds">
    <?php foreach ($htmlMedia as $media):
        echo $media->render();
    endforeach;
    ?>
        <p>&nbsp;</p>
    </div>
<?php endif; ?>

<h3>Instrument Information</h3>
<h4>Origins</h4>

<?php $origins = array(
    ['spatial', 'Continent'],
    ['source', 'Region'],
    ['coverage', 'Nation'],
    ['type', 'Formation']
  );
  foreach ($origins as $origin) {
      echo displayLinkToSolr($item, $origin, 'dcterms');
  }

?>

<h4>Classification (Sachs-Von Hornbostel revised by <a href="http://www.mimo-international.com/vocabulary.html">MIMO</a>)</h4>
<?php if ($item->value('dcterms:subject')) {
    echo displayLinkToSolr($item, 'subject', 'dcterms');  
}?>
    

<h4>Design and Playing Features</h4>

<?php

    $features = array(
        ['instrumentCategory', 'Category'],
        ['stringCarrierDesign', 'String carrier design'],
        ['resonatorDesignChordophone', 'Resonator design, chordophone'],
        ['stringCourses', 'String courses'],
        ['energyInputMotion', 'Energy input motion by performer'],
        ['vibrationalLength', 'Vibrational length'],
        ['stringTensionControl', 'String tension control'],
        ['methodOfSounding', 'Method of sounding'],
        ['pitchesPerStringCourse', 'Pitches per string course'],
        ['numberOfDrums', 'Number of drums comprising instrument'],
        ['shellDesign', 'Shell design'],
        ['numberAndFunctionofMembranes', 'Number and function of membranes'],
        ['membraneDesign', 'Membrane design'],
        ['membraneAttachment', 'Membrane attachment'],
        ['membraneTensionControl', 'Membrane tension control'],
        ['sounding', 'Sounding for membranophone'],
        ['soundModifiers', 'Sound modifiers for membranophone'],
        ['basicFormOfSonorousObjects', 'Basic form of sonorous object/s for idiophone'],
        ['soundObjectsPerInstrument', 'Sound objects per instrument'],
        ['resonatorDesign', 'Resonator design'],
        ['numberOfPlayers', 'Number of players'],
        ['soundingPrinciple', 'Sounding principle'],
        ['soundExcitingAgent', 'Sound exciting agent'],
        ['energyInputMotion', 'Energy input motion by performer'],
        ['pitchOfSound', 'Pitch of sound produced'],
        ['soundModification', 'Sound modification'],
        ['airCavityDesign', 'Air cavity design'],
        ['sourceAndDirectionOfAirstream', 'Source and direction of airstream'],
        ['energyTransducer', 'Energy transducer that activates sound'],
        ['meansOfModifyingStandingWave', 'Means of modifying shape and dimensions of standing wave in air cavity'],
        ['overblowingUtilization', 'Overblowing utilization'],
        ['pitchProduction', 'Pitch production']
    );

    foreach ($features as $feature) {
        echo displayLinkToSolr($item, $feature, 'wmi');
    }

    if ($item->value('dcterms:format')) {
        echo "<h4>Dimensions</h4>";
        echo "<p style=\"white-space:pre-wrap;\">" . $item->value('dcterms:format') . "</p>";
    }

    if ($item->value('dcterms:medium')) {
        echo "<h4>Primary Materials</h4><p>";
        foreach ($item->value('dcterms:medium',['all' => true]) as $medium) {
            echo displayLinkToSolrMulti('medium', 'dcterms', $medium) . "<br/>";
        }
        echo "</p>";
    }
?>

<?php if (count($otherMedia) > 0): ?>
<div id="other-media" class="property">
    <h4><?php echo $this->translate('Other Media'); ?></h4>
    <div class="values">
        <?php foreach($otherMedia as $media): ?>
        <div class="value">
            <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php $itemSets = $item->itemSets(); ?>
<?php if (count($itemSets) > 0): ?>
<div class="property">
    <h4><?php echo $this->translate('Item sets'); ?></h4>
    <div class="values">
        <?php foreach ($item->itemSets() as $itemSet): ?>
        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
