<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headScript()->appendFile($this->assetUrl('js/show.js'));
$this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));

$lightMedia = [];
$htmlMedia = [];
$audioMedia = [];
$otherMedia = [];
$whitelist = ['image/bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/svg+xml'];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if (in_array($mediaType, $whitelist) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else if (strpos($mediaRenderer, 'html') !== false) {
        $htmlMedia[] = $media;
    } else if (strpos($mediaType, 'audio/') !== false OR strpos($mediaType, 'video/') !== false) {
        $audioMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php if ($item->value('dcterms:alternative')) {
    echo "<p><strong><i>Also</i>: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
    foreach ($item->value('dcterms:alternative',['all' => true]) as $alttitle) {
	    echo $alttitle . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
    }
    echo "</p></strong>";
}?>
<?php if (count($lightMedia) > 0): ?>
<ul id="itemfiles" class="media-list">
    <?php foreach ($lightMedia as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
        <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>" data-sub-html="<p><?php echo $media->value('dcterms:alternative'); ?></p>" class="media resource">
	<?php if ($media->value('dcterms:title') || $media->value('dcterms:alternative')): ?>
            <div class="caption"><?php echo $media->value('dcterms:title') . ": " . $media->value('dcterms:alternative');?></div>
        <?php endif; ?>
            <?php echo $media->render(); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if (count($audioMedia) > 0): ?>
    <div class="media-embeds">
    <?php foreach ($audioMedia as $media):
        echo $media->render();
        echo $media->displayDescription();
        echo "<br /><br />";
    endforeach;
    ?>
    </div>
<?php endif; ?>

<?php if (count($htmlMedia) > 0): ?>
    <div class="html-embeds">
    <?php foreach ($htmlMedia as $media):
        echo $media->render();
    endforeach;
    ?>
        <p>&nbsp;</p>
    </div>
<?php endif; ?>

<div class="properties">
<?php $this->trigger('view.show.before'); ?>
<?php echo $item->displayValues(); ?>

<?php if (count($otherMedia) > 0): ?>
<div id="other-media" class="property">
    <h4><?php echo $this->translate('Other Media'); ?></h4>
    <div class="values">
        <?php foreach($otherMedia as $media): ?>
        <div class="value">
            <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>

<?php $itemSets = $item->itemSets(); ?>
<?php if (count($itemSets) > 0): ?>
<!--<div class="property">
    <h4><?php echo $this->translate('Item sets'); ?></h4>
    <div class="values">
        <?php foreach ($item->itemSets() as $itemSet): ?>
        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
    </div>
</div>-->
<?php endif; ?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
</div>
