<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->htmlElement('body')->setAttribute('onload', 'gridify()');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <script type="text/javascript">
          function gridify() {
           Search.setViewType('grid');
           console.log('Gridified!');
          }
        </script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <div id="wrap">
            <header>
                <h1>
                    <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="https://digital-grinnell.nyc3.digitaloceanspaces.com/omeka-s/digital-grinnell/asset/158b1d0621eeb5e9b9791b025eda8b6ea329fff5.png" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <?php echo $escape($siteTitle); ?>
                    <?php endif; ?>
                    </a>
                </h1>
                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>
    <div class="second-nav">            
        <ul class="navigation">
            <li><a href="https://www.grinnell.edu">Grinnell College</a></li>
            <li><a href="https://www.grinnell.edu/academics/majors-concentrations/music">Music at Grinnell</a></li>
    <form method="GET" action="&#x2F;s&#x2F;MusicalInstruments&#x2F;musical-instrument-search">
        <li>
        <label for="q">Search</label>
        <input type="text" name="q" placeholder="Search&#x20;items" value="">
    </li>
		<input type="hidden" name="limit[resource_class_s][0]" value="wmi:MusicalInstrument">
        </ul>
    </form>
    </div>
            </header>

            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer>
                
                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>
                <div class="second-nav">            
        <ul class="navigation">
            <li><a href="https://www.grinnell.edu">Grinnell College</a></li>
            <li><a href="https://www.grinnell.edu/academics/majors-concentrations/music">Music at Grinnell</a></li>
    <form method="GET" action="&#x2F;s&#x2F;MusicalInstruments&#x2F;musical-instrument-search">
        <li>
        <label for="q">Search</label>
        <input type="text" name="q" placeholder="Search&#x20;items" value="">
        </li>
            </form>
        </ul>
    </div>
                
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
            </footer>
        </div>
    </body>
</html>
